-- Pré-requisito para cadastrar filiais pelo painel administrativo.
-- Execute uma vez no SQL Editor do Supabase antes de publicar a interface.
-- A política RLS regional_filiais_insert/update continua limitando gravações
-- à conta superadministradora. Este script não remove nem altera filiais.

begin;

do $block$
declare
  v_identity text;
  v_default text;
  v_sequence text;
  v_max_id bigint;
  v_criou_identity boolean := false;
begin
  select is_identity, column_default
    into v_identity, v_default
  from information_schema.columns
  where table_schema = 'public'
    and table_name = 'filiais'
    and column_name = 'id';

  if not found then
    raise exception 'Coluna public.filiais.id não encontrada.';
  end if;

  -- Bancos antigos podem ter ID manual sem sequence/default.
  if v_identity = 'NO' and v_default is null then
    alter table public.filiais
      alter column id add generated by default as identity;
    v_criou_identity := true;
  end if;

  v_sequence := pg_get_serial_sequence('public.filiais', 'id');
  if v_sequence is null then
    raise exception 'Não foi possível localizar/criar a sequence de public.filiais.id.';
  end if;

  -- Se a sequence acabou de ser criada sobre IDs existentes, posiciona-a após
  -- o maior ID para evitar colisões nos próximos cadastros.
  if v_criou_identity then
    select max(id) into v_max_id from public.filiais;
    if v_max_id is null then
      perform setval(v_sequence::regclass, 1, false);
    else
      perform setval(v_sequence::regclass, v_max_id, true);
    end if;
  end if;

  execute format('grant usage, select on sequence %s to authenticated', v_sequence::regclass);
end;
$block$;

grant select, insert, update on table public.filiais to authenticated;

commit;
